//! Code generation from the type schema.
//!
//! The [`Generator`] trait is the same abstraction the GUI drives from its
//! `Field` objects; here it also powers [`generate`], which emits code straight
//! from a headless [`Project`].

use crate::schema::Project;
use crate::types::FieldKind;
use std::borrow::Cow;

/// Sink that turns a sequence of class/field/offset events into source text.
pub trait Generator {
    /// Begin a class named `name`.
    fn begin_class(&mut self, name: &str);
    /// End the current class.
    fn end_class(&mut self);
    /// Add a field of `kind` (with optional `metadata`, e.g. a pointer's target type).
    fn add_field(&mut self, name: &str, kind: FieldKind, metadata: Option<&str>);
    /// Advance the current offset by `offset` bytes (emits padding as needed).
    fn add_offset(&mut self, offset: usize);
    /// Consume accumulated output.
    fn finilize(&mut self) -> String;
}

/// A code-generation target language.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub enum Lang {
    /// Rust `#[repr(C)]` structs.
    #[default]
    Rust,
    /// C++ classes.
    Cpp,
}

impl Lang {
    /// All languages, for menus.
    pub const ALL: &'static [Lang] = &[Lang::Rust, Lang::Cpp];

    /// Human label.
    pub fn label(&self) -> &'static str {
        match self {
            Self::Rust => "Rust",
            Self::Cpp => "C++",
        }
    }

    /// Constructs the matching boxed generator.
    pub fn generator(&self) -> Box<dyn Generator> {
        match self {
            Self::Rust => Box::<RustGenerator>::default(),
            Self::Cpp => Box::<CppGenerator>::default(),
        }
    }

    /// Parses a language from a short name (`"rust"`, `"cpp"`/`"c++"`).
    pub fn parse(s: &str) -> Option<Self> {
        match s.to_ascii_lowercase().as_str() {
            "rust" | "rs" => Some(Self::Rust),
            "cpp" | "c++" | "cxx" => Some(Self::Cpp),
            _ => None,
        }
    }
}

/// Generates source text for `project` in `lang`, driving a fresh generator
/// from the flat schema (fields sorted by offset, gaps emitted as padding).
pub fn generate(project: &Project, lang: Lang) -> String {
    let mut generator = lang.generator();
    drive(project, generator.as_mut());
    generator.finilize()
}

/// Feeds `project`'s classes/fields into `sink` (without finalizing), so callers
/// with a custom [`Generator`] can reuse the schema-walking logic.
pub fn drive(project: &Project, sink: &mut dyn Generator) {
    for class in &project.classes {
        sink.begin_class(&class.name);

        let mut fields = class.fields.clone();
        fields.sort_by_key(|f| f.offset);

        let mut cursor = 0usize;
        for f in &fields {
            if f.offset > cursor {
                sink.add_offset(f.offset - cursor);
            }
            sink.add_field(&f.name, f.kind, f.metadata.as_deref());
            cursor = f.offset + f.kind.size();
        }

        sink.end_class();
    }
}

const HEADER: &str = concat!(
    "// Generated by nemclass ",
    env!("CARGO_PKG_VERSION"),
    "\n// Made by @ItsEthra\n\n"
);

/// Emits Rust `#[repr(C)]` structs.
pub struct RustGenerator {
    text: String,
    last_offset: usize,
    offset: usize,
}

impl Default for RustGenerator {
    fn default() -> Self {
        Self {
            text: HEADER.to_owned(),
            last_offset: 0,
            offset: 0,
        }
    }
}

impl Generator for RustGenerator {
    fn begin_class(&mut self, name: &str) {
        self.text += &format!("#[repr(C)]\npub struct {name} {{\n");
    }

    fn end_class(&mut self) {
        self.text += "}\n\n";
        self.offset = 0;
        self.last_offset = 0;
    }

    fn add_field(&mut self, name: &str, kind: FieldKind, metadata: Option<&str>) {
        let size = kind.size();
        if self.offset != self.last_offset {
            self.text += &format!(
                "    _pad_0x{:x}: [u8; 0x{:x}],\n",
                self.offset,
                self.offset - self.last_offset
            );
        }

        self.text += &format!("    pub {name}: {},\n", rust_ty(kind, metadata));

        self.offset += size;
        self.last_offset = self.offset;
    }

    fn add_offset(&mut self, offset: usize) {
        self.offset += offset;
    }

    fn finilize(&mut self) -> String {
        std::mem::take(&mut self.text)
    }
}

fn rust_ty(kind: FieldKind, metadata: Option<&str>) -> Cow<'static, str> {
    match kind {
        FieldKind::Unk8 | FieldKind::Unk16 | FieldKind::Unk32 | FieldKind::Unk64 => {
            // Padded away by add_offset in normal use; be lenient if reached.
            "u8".into()
        }
        FieldKind::I8 => "i8".into(),
        FieldKind::U8 => "u8".into(),
        FieldKind::I16 => "i16".into(),
        FieldKind::U16 => "u16".into(),
        FieldKind::I32 => "i32".into(),
        FieldKind::U32 => "u32".into(),
        FieldKind::I64 => "i64".into(),
        FieldKind::U64 => "u64".into(),
        FieldKind::F32 => "f32".into(),
        FieldKind::F64 => "f64".into(),
        FieldKind::Ptr => format!("Option<&'static {}>", metadata.unwrap_or("()")).into(),
        FieldKind::StrPtr => "*const u8".into(),
        FieldKind::Bool => "bool".into(),
        FieldKind::Vector { components, width } => {
            format!("[{}; {}]", width.rust_ty(), components).into()
        }
        FieldKind::Matrix { rows, cols, width } => {
            format!("[[{}; {}]; {}]", width.rust_ty(), cols, rows).into()
        }
    }
}

/// Emits C++ classes.
pub struct CppGenerator {
    predecls: String,
    main: String,
    offset: usize,
    last_offset: usize,
}

impl Default for CppGenerator {
    fn default() -> Self {
        Self {
            predecls: format!("{HEADER}#include <cstdint>\n\n"),
            main: String::new(),
            offset: 0,
            last_offset: 0,
        }
    }
}

impl Generator for CppGenerator {
    fn begin_class(&mut self, name: &str) {
        self.predecls += &format!("class {name};\n");
        self.main += &format!("class {name} {{\npublic:\n");
    }

    fn end_class(&mut self) {
        self.main += "};\n\n";
        self.offset = 0;
        self.last_offset = 0;
    }

    fn add_field(&mut self, name: &str, kind: FieldKind, metadata: Option<&str>) {
        let size = kind.size();
        if self.offset != self.last_offset {
            self.main += &format!(
                "    char _pad0x{:x}[0x{:x}];\n",
                self.offset,
                self.offset - self.last_offset
            );
        }

        self.main += &format!(
            "    {} {name}{};\n",
            cpp_ty(kind, metadata),
            cpp_array_suffix(kind)
        );

        self.offset += size;
        self.last_offset = self.offset;
    }

    fn add_offset(&mut self, offset: usize) {
        self.offset += offset;
    }

    fn finilize(&mut self) -> String {
        std::mem::take(&mut self.predecls) + "\n" + &std::mem::take(&mut self.main)
    }
}

fn cpp_ty(kind: FieldKind, metadata: Option<&str>) -> Cow<'static, str> {
    match kind {
        FieldKind::Unk8 | FieldKind::Unk16 | FieldKind::Unk32 | FieldKind::Unk64 => {
            "uint8_t".into()
        }
        FieldKind::I8 => "int8_t".into(),
        FieldKind::U8 => "uint8_t".into(),
        FieldKind::I16 => "int16_t".into(),
        FieldKind::U16 => "uint16_t".into(),
        FieldKind::I32 => "int32_t".into(),
        FieldKind::U32 => "uint32_t".into(),
        FieldKind::I64 => "int64_t".into(),
        FieldKind::U64 => "uint64_t".into(),
        FieldKind::F32 => "float".into(),
        FieldKind::F64 => "double".into(),
        FieldKind::Ptr => format!("{}*", metadata.unwrap_or("void")).into(),
        FieldKind::StrPtr => "const char*".into(),
        FieldKind::Bool => "bool".into(),
        FieldKind::Vector { width, .. } | FieldKind::Matrix { width, .. } => width.cpp_ty().into(),
    }
}

/// C++ array declarator placed after the field name (`float name[3];`, `float m[4][4];`).
fn cpp_array_suffix(kind: FieldKind) -> Cow<'static, str> {
    match kind {
        FieldKind::Vector { components, .. } => format!("[{components}]").into(),
        FieldKind::Matrix { rows, cols, .. } => format!("[{rows}][{cols}]").into(),
        _ => "".into(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::TypeBuilder;
    use crate::types::FloatWidth;

    fn camera_project() -> Project {
        let mut project = Project::new();
        let mut b = TypeBuilder::new("Camera");
        b.field("pos", FieldKind::Vector { components: 3, width: FloatWidth::F32 })
            .field("view", FieldKind::Matrix { rows: 4, cols: 4, width: FloatWidth::F64 });
        project.classes.push(b.build());
        project
    }

    #[test]
    fn rust_codegen() {
        let out = generate(&camera_project(), Lang::Rust);
        assert!(out.contains("pub pos: [f32; 3]"), "{out}");
        assert!(out.contains("pub view: [[f64; 4]; 4]"), "{out}");
    }

    #[test]
    fn cpp_codegen() {
        let out = generate(&camera_project(), Lang::Cpp);
        assert!(out.contains("float pos[3];"), "{out}");
        assert!(out.contains("double view[4][4];"), "{out}");
    }
}
