use crate::{
    class::ClassList, config::YClassConfig, context::Selection, hotkeys::HotkeyManager,
    process::Process, project::ProjectData,
};
use nemclass_sdk::{CheatTable, Manifest, Target};
use egui_notify::Toasts;
use parking_lot::RwLock;
use std::{
    cell::RefCell,
    collections::HashSet,
    path::{Path, PathBuf},
    sync::Arc,
};

pub type StateRef = &'static RefCell<GlobalState>;

/// Maximum number of undo steps kept in memory.
const MAX_UNDO: usize = 100;

pub struct GlobalState {
    /// The open project *folder* (contains `project.nemproj`), if any.
    pub last_opened_project: Option<PathBuf>,
    /// The open project's manifest (name + optional auto-attach).
    pub manifest: Manifest,
    pub selection: Option<Selection>,
    pub process: Arc<RwLock<Option<Process>>>,
    /// The project's cheat table (address + type + freeze entries). Shared so the
    /// scanner can add hits and the cheat-table window can edit/freeze them.
    pub cheat_table: CheatTable,
    pub hotkeys: HotkeyManager,
    pub class_list: ClassList,
    pub config: YClassConfig,
    pub toasts: Toasts,
    /// `true` means project was just created and contains no useful
    /// information
    pub dummy: bool,
    /// Undo/redo history of class-list snapshots (structure only, not process memory).
    pub undo_stack: Vec<ClassList>,
    pub redo_stack: Vec<ClassList>,
}

/// Pushes a snapshot of `class_list` onto `undo_stack` (capped) and clears `redo_stack`. Free
/// function so callers holding a disjoint borrow of `GlobalState` (e.g. the inspector's process
/// read-guard) can snapshot without a full `&mut self`.
pub fn push_class_list_snapshot(
    undo_stack: &mut Vec<ClassList>,
    redo_stack: &mut Vec<ClassList>,
    class_list: &ClassList,
) {
    undo_stack.push(class_list.deep_clone());
    if undo_stack.len() > MAX_UNDO {
        undo_stack.remove(0);
    }
    redo_stack.clear();
}

impl Default for GlobalState {
    fn default() -> Self {
        let config = YClassConfig::load_or_default();

        Self {
            hotkeys: HotkeyManager::default(),
            class_list: ClassList::default(),
            last_opened_project: None,
            manifest: Manifest::new("untitled"),
            toasts: Toasts::default(),
            process: Arc::default(),
            cheat_table: CheatTable::new(),
            selection: None,
            dummy: true,
            config,
            undo_stack: vec![],
            redo_stack: vec![],
        }
    }
}

impl GlobalState {
    /// Snapshots the current class list so the next mutation can be undone. Call this *before*
    /// mutating the class list.
    pub fn push_undo(&mut self) {
        push_class_list_snapshot(&mut self.undo_stack, &mut self.redo_stack, &self.class_list);
    }

    /// Reverts to the previous class-list snapshot, pushing the current state onto the redo stack.
    pub fn undo(&mut self) {
        if let Some(prev) = self.undo_stack.pop() {
            self.redo_stack.push(self.class_list.deep_clone());
            self.class_list = prev;
            // Field ids are regenerated by the snapshot, so any field-level selection is stale.
            self.selection = None;
            self.dummy = false;
        } else {
            self.toasts.info("Nothing to undo");
        }
    }

    /// Re-applies the most recently undone change.
    pub fn redo(&mut self) {
        if let Some(next) = self.redo_stack.pop() {
            self.undo_stack.push(self.class_list.deep_clone());
            self.class_list = next;
            self.selection = None;
            self.dummy = false;
        } else {
            self.toasts.info("Nothing to redo");
        }
    }

    /// Creates a new project in a chosen (existing) folder, scaffolding
    /// `project.nemproj`, `classes/` and `scripts/`.
    pub fn new_project(&mut self) {
        if self.last_opened_project.is_some() && !self.dummy {
            self.save_project(None);
        }

        let Some(dir) = rfd::FileDialog::new()
            .set_title("Choose a folder for the new project")
            .pick_folder()
        else {
            return;
        };

        let name = dir
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("project")
            .to_owned();

        match nemclass_sdk::project::create_dir(&dir, &name) {
            Ok(loaded) => {
                // Scaffold Lua editor autocompletion (scripts/nem.lua + .luarc.json).
                let _ = nemclass_scripting::write_editor_support(&dir);
                self.class_list = ClassList::default();
                self.manifest = loaded.manifest;
                self.cheat_table = CheatTable::new();
                self.last_opened_project = Some(dir.clone());
                self.dummy = false;
                self.remember_recent(&dir);
                self.config.save();
            }
            Err(e) => {
                self.toasts
                    .error(format!("Failed to create the project. {e}"));
            }
        }
    }

    pub fn save_project_as(&mut self) {
        if let Some(dir) = rfd::FileDialog::new()
            .set_title("Save project to folder")
            .pick_folder()
        {
            self.save_project(Some(&dir));
        }
    }

    pub fn save_project(&mut self, dir: Option<&Path>) {
        let dir = match dir
            .map(Path::to_path_buf)
            .or_else(|| self.last_opened_project.clone())
        {
            Some(d) => d,
            None => match rfd::FileDialog::new()
                .set_title("Save project to folder")
                .pick_folder()
            {
                Some(d) => d,
                None => return,
            },
        };

        let project = ProjectData::store(self.class_list.classes()).into_project();
        match nemclass_sdk::project::save_dir(&dir, &self.manifest, &project) {
            Ok(()) => {
                // save_dir created tables/; persist the cheat table alongside classes.
                let _ = self.cheat_table.save(&Self::cheat_table_path(&dir));
                self.last_opened_project = Some(dir);
                self.dummy = false;
            }
            Err(e) => {
                self.toasts
                    .error(format!("Failed to save the project. {e}"));
            }
        }
    }

    pub fn open_project(&mut self) -> bool {
        if let Some(dir) = rfd::FileDialog::new()
            .set_title("Open project folder")
            .pick_folder()
        {
            self.open_project_path(&dir)
        } else {
            true
        }
    }

    pub fn open_project_path(&mut self, dir: &Path) -> bool {
        // Persist the current project before switching away from it.
        if self.last_opened_project.is_some() && !self.dummy {
            self.save_project(None);
        }

        if !nemclass_sdk::project::is_project_dir(dir) {
            self.toasts
                .error("Folder is not a nemclass project (missing project.nemproj)");
            return false;
        }

        match nemclass_sdk::project::load_dir(dir) {
            Ok(loaded) => {
                self.class_list = ProjectData::from_project(loaded.classes).load();
                self.manifest = loaded.manifest;
                let table_path = Self::cheat_table_path(dir);
                self.cheat_table = if table_path.is_file() {
                    CheatTable::load(&table_path).unwrap_or_default()
                } else {
                    CheatTable::new()
                };
                self.last_opened_project = Some(dir.to_path_buf());
                self.dummy = false;
                self.remember_recent(dir);
                self.config.save();
                self.attach_from_manifest();
                true
            }
            Err(e) => {
                self.toasts
                    .error(format!("Failed to open the project. {e}"));
                false
            }
        }
    }

    /// The `scripts/` directory of the open project, if any.
    pub fn scripts_dir(&self) -> Option<PathBuf> {
        self.last_opened_project
            .as_ref()
            .map(|dir| dir.join(nemclass_sdk::project::SCRIPTS_DIR))
    }

    /// The cheat-table file (`tables/table.ron`) inside `dir`.
    fn cheat_table_path(dir: &Path) -> PathBuf {
        dir.join(nemclass_sdk::project::TABLES_DIR).join("table.ron")
    }

    fn remember_recent(&mut self, dir: &Path) {
        if let Some(recent) = self.config.recent_projects.as_mut() {
            recent.insert(dir.to_path_buf());
        } else {
            self.config.recent_projects = Some(HashSet::from_iter([dir.to_path_buf()]));
        }
    }

    /// Attempts the manifest's auto-attach, if configured. Errors surface as toasts.
    pub fn attach_from_manifest(&mut self) {
        let Some(spec) = self.manifest.auto_attach.clone() else {
            return;
        };
        match Target::from_auto_attach(&spec) {
            Ok(target) => {
                *self.process.write() = Some(Process::from_target(target));
                self.toasts
                    .info(format!("Auto-attached to {}", spec.process_name));
            }
            Err(e) => {
                self.toasts.warning(format!("Auto-attach failed: {e}"));
            }
        }
    }
}
