use crate::{
    class::ClassList, config::YClassConfig, context::Selection, hotkeys::HotkeyManager,
    process::Process, project::ProjectData,
};
use egui_notify::Toasts;
use parking_lot::RwLock;
use std::{
    cell::RefCell,
    collections::HashSet,
    fs,
    path::{Path, PathBuf},
    sync::Arc,
};

pub type StateRef = &'static RefCell<GlobalState>;

/// Maximum number of undo steps kept in memory.
const MAX_UNDO: usize = 100;

pub struct GlobalState {
    pub last_opened_project: Option<PathBuf>,
    pub selection: Option<Selection>,
    pub process: Arc<RwLock<Option<Process>>>,
    pub hotkeys: HotkeyManager,
    pub class_list: ClassList,
    pub config: YClassConfig,
    pub toasts: Toasts,
    /// `true` means project was just created and contains no useful
    /// information
    pub dummy: bool,
    /// Undo/redo history of class-list snapshots (structure only, not process memory).
    pub undo_stack: Vec<ClassList>,
    pub redo_stack: Vec<ClassList>,
}

/// Pushes a snapshot of `class_list` onto `undo_stack` (capped) and clears `redo_stack`. Free
/// function so callers holding a disjoint borrow of `GlobalState` (e.g. the inspector's process
/// read-guard) can snapshot without a full `&mut self`.
pub fn push_class_list_snapshot(
    undo_stack: &mut Vec<ClassList>,
    redo_stack: &mut Vec<ClassList>,
    class_list: &ClassList,
) {
    undo_stack.push(class_list.deep_clone());
    if undo_stack.len() > MAX_UNDO {
        undo_stack.remove(0);
    }
    redo_stack.clear();
}

impl Default for GlobalState {
    fn default() -> Self {
        let config = YClassConfig::load_or_default();

        Self {
            hotkeys: HotkeyManager::default(),
            class_list: ClassList::default(),
            last_opened_project: None,
            toasts: Toasts::default(),
            process: Arc::default(),
            selection: None,
            dummy: true,
            config,
            undo_stack: vec![],
            redo_stack: vec![],
        }
    }
}

impl GlobalState {
    /// Snapshots the current class list so the next mutation can be undone. Call this *before*
    /// mutating the class list.
    pub fn push_undo(&mut self) {
        push_class_list_snapshot(&mut self.undo_stack, &mut self.redo_stack, &self.class_list);
    }

    /// Reverts to the previous class-list snapshot, pushing the current state onto the redo stack.
    pub fn undo(&mut self) {
        if let Some(prev) = self.undo_stack.pop() {
            self.redo_stack.push(self.class_list.deep_clone());
            self.class_list = prev;
            // Field ids are regenerated by the snapshot, so any field-level selection is stale.
            self.selection = None;
            self.dummy = false;
        } else {
            self.toasts.info("Nothing to undo");
        }
    }

    /// Re-applies the most recently undone change.
    pub fn redo(&mut self) {
        if let Some(next) = self.redo_stack.pop() {
            self.undo_stack.push(self.class_list.deep_clone());
            self.class_list = next;
            self.selection = None;
            self.dummy = false;
        } else {
            self.toasts.info("Nothing to redo");
        }
    }

    pub fn save_project_as(&mut self) {
        if let Some(path) = rfd::FileDialog::new()
            .set_title("Save current project")
            .add_filter("YClass project", &["yclass"])
            .save_file()
        {
            self.save_project(Some(&path));
        }
    }

    pub fn save_project(&mut self, path: Option<&Path>) {
        if let Some(path) = path {
            let pd = ProjectData::store(self.class_list.classes()).to_string();
            if let Err(e) = fs::write(path, pd.as_bytes()) {
                self.toasts
                    .error(format!("Failed to save the project. {e}"));
            } else {
                self.last_opened_project = Some(path.to_owned());
                self.dummy = false;
            }
        } else if let Some(ref last) = self.last_opened_project {
            let pd = ProjectData::store(self.class_list.classes()).to_string();
            if let Err(e) = fs::write(last, pd.as_bytes()) {
                self.toasts
                    .error(format!("Failed to save the project. {e}"));
            } else {
                self.last_opened_project = Some(last.to_owned());
                self.dummy = false;
            }
        } else if let Some(path) = rfd::FileDialog::new()
            .set_title("Save current project")
            .add_filter("YClass project", &["yclass"])
            .save_file()
        {
            self.save_project(Some(&path));
        }
    }

    pub fn open_project(&mut self) -> bool {
        if let Some(path) = rfd::FileDialog::new()
            .set_title("Open existing project")
            .add_filter("YClass project", &["yclass"])
            .pick_file()
        {
            self.open_project_path(&path)
        } else {
            true
        }
    }

    pub fn open_project_path(&mut self, path: &Path) -> bool {
        if !self.class_list.classes().is_empty() && !self.dummy {
            self.save_project(None);
        }

        match fs::read_to_string(path) {
            Ok(data) => {
                if let Some(pd) = ProjectData::from_str(&data) {
                    self.class_list = pd.load();
                    self.dummy = false;
                    self.last_opened_project = Some(path.to_path_buf());

                    if let Some(recent) = self.config.recent_projects.as_mut() {
                        recent.insert(path.to_path_buf());
                    } else {
                        self.config.recent_projects =
                            Some(HashSet::from_iter([path.to_path_buf()]));
                    }
                    self.config.save();

                    true
                } else {
                    self.toasts.error("Project file is in invalid format");
                    false
                }
            }
            Err(e) => {
                self.toasts
                    .error(format!("Failed to open the project. {e}"));
                false
            }
        }
    }
}
